module.exports = {
  // 400 ERRORS
  BAD_REQUEST: 'BAD_REQUEST',

  // 401 ERRORS
  UNAUTHORIZED: 'UNAUTHORIZED',

  // 403 ERRORS
  FORBIDDEN: 'FORBIDDEN',

  // 404 ERRORS
  NOT_FOUND: 'NOT_FOUND',

  // 409 ERRORS
  CONFLICT: 'CONFLICT',
};
