openapi: 3.0.0
info:
  title: StuCode API
  description: |
    RacketOnDeck is a versatile platform designed to streamline the management of padel academies.

    From handling user accounts to managing court bookings, RacketOnDeck provides a comprehensive suite of tools to
    enhance the efficiency and experience of both academy staff and players. 🎾🏆📅
  version: 1.0.0
servers:
  - url: /v1
tags:
  - name: Accounts 📝
    description: Operations related to managing user accounts.

paths:
  !!inc/dir ['.', { whitelist: 'paths', blacklist: ['api', 'schemas', 'requestBodies', 'responses'] }]
components:
  schemas:
    !!inc/dir ['.', { whitelist: 'schemas', blacklist: ['api', 'paths', 'requestBodies', 'responses'] }]
  responses:
    !!inc/dir ['.', { whitelist: 'responses', blacklist: ['api', 'paths', 'schemas', 'requestBodies'] }]
